variant = "loose"

[[issues]]
file = "src/Adapter/MessageInterface.php"
code = "too-many-methods"
message = "Interface has too many methods."
count = 1

[[issues]]
file = "src/Adapter/MessageInterface.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "src/Adapter/PhpMailer.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1
